[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup=1
let g:deoplete#auto_complete_delay=10
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
hook_source = '''
let g:python3_host_prog = "/usr/local/bin/python3"
let g:python_host_prog = "/usr/local/bin/python"
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'

[[plugins]]
repo = 'plasticboy/vim-markdown'
hook_add = 'let g:vim_markdown_folding_disabled=1'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'othree/yajs.vim'
#on_ft = ['javascript', 'html', 'php']

[[plugins]]
repo = 'pangloss/vim-javascript'
#on_ft = ['javascript']
hook_add = '''
let g:jsx_ext_required = 0
'''

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
#on_ft = ['javascript']

[[plugins]]
repo = 'moll/vim-node'
#on_ft = ['javascript']

[[plugins]]
repo = 'myhere/vim-nodejs-complete'
#on_ft = ['javascript']
hook_add = '''
  setl omnifunc=jscomplete#CompleteJS
  if !exists('g:neocomplcache_omni_functions')
    let g:neocomplcache_omni_functions = {}
  endif
  let g:neocomplcache_omni_functions.javascript = 'nodejscomplete#CompleteJS'
  let g:node_usejscomplete = 1
'''

[[plugins]]
repo = 'w0rp/ale.git'
on_source = ['lightline.vim']
hook_add = '''
  let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '']
'''
